Implement Navigation Bar
naurffxiv/naurffxiv pull request #34
Opened 2024-11-14 21:29 UTC by brtran4

This commit lays out the fundamentals for what we need from the Navigation Bar. A later commit will be pushed out when specific theming is set.

This is what the navigation bar currently looks like

<img width="1199" alt="Screenshot 2024-11-14 at 1 36 10 PM" src="https://github.com/user-attachments/assets/1c4ec891-2b9a-475d-9217-3b7560e3073e">

Ticket: NAUR-23

2024-11-14 21:39 UTC, clairefleuret requested changes
I think we can actually remove the About us section and utilize the Homepage to define our mission/goals as we already are

2024-11-14 21:57 UTC, brtran4 commented
> I think we can actually remove the About us section and utilize the Homepage to define our mission/goals as we already are

<img width="1197" alt="Screenshot 2024-11-14 at 1 56 48 PM" src="https://github.com/user-attachments/assets/1cbde635-8982-4d53-b592-90437ce076f2">

updated to also include the icon to link back to the home page

2024-11-14 22:01 UTC, clairefleuret approved these changes

2024-12-18 01:29 UTC, brtran4 commented
new navbar

![Screenshot 2024-12-17 at 8 29 33 PM](https://github.com/user-attachments/assets/38cd15a8-eadb-4c40-82af-844cafc4fcf0)

2024-12-18 01:30 UTC, merged